# Generated by Django 5.2.16 on 2026-07-15 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
