# Generated by Django 5.2.16 on 2026-07-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_codesnippet_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='is_public',
        ),
    ]
