# Generated by Django 5.2.16 on 2026-08-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_device_scoped'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codesnippet',
            new_name='snippet_device_recent_idx',
            old_name='snippets_co_device__0f3a1c_idx',
        ),
    ]
